import DashboardLayout from '@/components/DashboardLayout';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { useSupabaseAuth } from '@/contexts/SupabaseAuthContext';
import { auditApi, SavedAudit } from '@/lib/audit-api';
import { overviewMetrics, prioritizedIssues, recentAudits } from '@/lib/dashboard-summary';
import { auditIdFromLocation, routeSection } from '@/lib/audit-view';
import { connectionStateFromResponse, locateSucceeded, type ExtensionConnectionState } from '@/lib/extension-bridge';
import { AlertTriangle, CheckCircle2, ChevronRight, CircleAlert, ExternalLink, Loader2, LocateFixed, LogIn, Plus, RefreshCw, Wifi } from 'lucide-react';
import { FormEvent, ReactNode, useCallback, useEffect, useState } from 'react';
import { useLocation } from 'wouter';

const scoreTone = (score?: number | null) => score == null ? 'text-slate-500' : score >= 80 ? 'text-emerald-300' : score >= 50 ? 'text-amber-300' : 'text-rose-300';
const source = (value: string) => <Badge variant="outline" className="font-mono text-[10px] tracking-wider">{value}</Badge>;
const formatCaptured = (value?: string) => value ? new Date(value).toLocaleString() : 'Capture time unavailable';

function SignIn() {
  const { configured, signIn, signUp } = useSupabaseAuth();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState<string | null>(null); const [working, setWorking] = useState(false);
  async function submit(event: FormEvent, mode: 'in' | 'up') { event.preventDefault(); setWorking(true); setError(mode === 'in' ? await signIn(email, password) : await signUp(email, password)); setWorking(false); }
  return <main className="grid min-h-screen place-items-center bg-background p-5 text-foreground"><Card className="w-full max-w-md border-white/[.12] bg-[#0c1823] shadow-2xl"><CardHeader><CardTitle className="text-2xl">Sign in to AuditFlux</CardTitle><p className="text-sm text-muted-foreground">Use your AuditFlux Supabase account to access saved evidence.</p></CardHeader><CardContent>{!configured ? <p className="rounded-md border border-amber-300/30 bg-amber-300/10 p-3 text-sm text-amber-100">Supabase client configuration is required before production sign-in can be used.</p> : <form className="space-y-3"><Input type="email" required placeholder="you@example.com" value={email} onChange={event => setEmail(event.target.value)} /><Input type="password" required minLength={6} placeholder="Password" value={password} onChange={event => setPassword(event.target.value)} />{error && <p className="text-sm text-rose-300">{error}</p>}<div className="grid grid-cols-2 gap-3"><Button disabled={working} onClick={event => void submit(event, 'in')}><LogIn className="mr-2 h-4 w-4" />Sign in</Button><Button type="button" variant="outline" disabled={working} onClick={event => void submit(event, 'up')}>Create account</Button></div></form>}</CardContent></Card></main>;
}

function Empty({ title }: { title: string }) { return <Card className="border-dashed border-white/[.16] bg-[#0c1823]/70"><CardContent className="p-10 text-center text-sm text-slate-400">{title}</CardContent></Card>; }
function DataTable({ rows, fields, empty }: { rows: Record<string, any>[]; fields: [string, (row: Record<string, any>) => ReactNode][]; empty: string }) { return rows.length ? <div className="overflow-x-auto rounded-xl border border-white/[.10] bg-[#0c1823]/70"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-white/[.035] text-xs uppercase tracking-wider text-slate-400"><tr>{fields.map(([label]) => <th key={label} className="px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row.id || index} className="border-t border-white/[.06] hover:bg-white/[.025]">{fields.map(([label, render]) => <td key={label} className="px-4 py-3 align-top">{render(row)}</td>)}</tr>)}</tbody></table></div> : <Empty title={empty} />; }

function Overview({ audit, selected, history, userName, onOpenAudit, onConnect }: { audit: Record<string, any>; selected: SavedAudit; history: Record<string, any>[]; userName: string; onOpenAudit: (id: string) => void; onConnect: () => void }) {
  const metrics = overviewMetrics(audit, selected.performance || []); const issues = prioritizedIssues(selected.issues || []); const audits = recentAudits(history);
  return <><section className="af-hero"><div className="af-hero-copy"><p className="af-kicker">Workspace overview</p><h2>Good to see you, {userName}.</h2><p>Your latest saved audit is ready for review. Prioritize the measured issues below, then use the extension to collect fresh evidence.</p><div className="af-hero-meta"><span className="af-live-dot" />Last saved audit: {formatCaptured(audit.captured_at)}</div></div><Button className="af-hero-action" onClick={onConnect}><Wifi className="mr-2 h-4 w-4" />Connect extension</Button></section><section className="af-metric-grid" aria-label="Latest saved audit metrics">{metrics.map(metric => <article key={metric.label} className={`af-metric-card ${metric.tone}`}><p>{metric.label}</p><strong>{metric.value ?? '—'}</strong><em>{metric.value == null ? 'Not captured' : metric.tone === 'good' ? 'Measured' : metric.tone === 'critical' ? 'Needs review' : 'Review'}</em></article>)}</section><div className="af-overview-grid"><section className="af-panel"><header className="af-panel-heading"><div><p>Audit history</p><h3>Recent audits</h3></div><button className="af-open-link" onClick={() => onOpenAudit(history[0]?.id)}>View all <ChevronRight className="inline h-3.5 w-3.5" /></button></header>{audits.length ? <div className="overflow-x-auto"><table className="af-audit-table"><thead><tr><th>URL</th><th>Score</th><th>Issues</th><th>Completed</th><th /></tr></thead><tbody>{audits.map(row => <tr key={row.id}><td><div className="af-url"><strong>{row.url}</strong><em>Saved evidence</em></div></td><td><span className={`af-score ${(row.score ?? 0) < 80 ? 'fair' : ''}`}>{row.score ?? '—'}</span></td><td>{row.issues ?? '—'}</td><td>{formatCaptured(row.capturedAt)}</td><td><button className="af-open-link" onClick={() => onOpenAudit(row.id)}>Open</button></td></tr>)}</tbody></table></div> : <div className="p-7 text-sm text-slate-400">No saved audits yet. Use the AuditFlux extension to capture the first real audit.</div>}</section><section className="af-panel"><header className="af-panel-heading"><div><p>Prioritized queue</p><h3>Issues overview</h3></div><button className="af-open-link" onClick={() => onOpenAudit(audit.id)}>View report <ChevronRight className="inline h-3.5 w-3.5" /></button></header><div className="af-issue-list">{issues.length ? issues.map(issue => <button key={issue.id} className="af-issue-row" onClick={() => onOpenAudit(audit.id)}><span className={`af-severity ${issue.severity}`}><CircleAlert size={15} /></span><span className="af-issue-copy"><strong>{issue.title}</strong><span>{issue.detail}</span></span><ChevronRight className="af-issue-arrow" size={17} /></button>) : <p className="p-5 text-sm text-slate-400">No saved issues are available for this audit.</p>}</div></section></div></>;
}

export default function Home() {
  const { user, session, loading } = useSupabaseAuth(); const [location, setLocation] = useLocation(); const [history, setHistory] = useState<Record<string, any>[]>([]); const [projects, setProjects] = useState<Record<string, any>[]>([]); const [selected, setSelected] = useState<SavedAudit | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(true); const [selectedIssue, setSelectedIssue] = useState<Record<string, any> | null>(null); const [extensionConnection, setExtensionConnection] = useState<ExtensionConnectionState>('unknown'); const [locateNotice, setLocateNotice] = useState<string | null>(null);
  const token = session?.access_token; const selectedId = auditIdFromLocation(location) || selected?.audit?.id;
  const refresh = useCallback(async () => { if (!token) return; try { const [historyResult, projectResult] = await Promise.all([auditApi.history(token), auditApi.projects(token)]); setHistory(historyResult.audits); setProjects(projectResult.projects); const target = selectedId || historyResult.audits[0]?.id; setSelected(target ? await auditApi.audit(token, target) : null); setError(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load saved audits.'); } finally { setBusy(false); } }, [token, selectedId]);
  useEffect(() => { void refresh(); }, [refresh]); useEffect(() => { if (!token) return; const timer = window.setInterval(() => void refresh(), 15000); return () => window.clearInterval(timer); }, [token, refresh]);
  if (loading) return <main className="grid min-h-screen place-items-center bg-background"><Loader2 className="animate-spin text-primary" /></main>; if (!user) return <SignIn />;
  const section = routeSection(location); const audit = selected?.audit; const payload = audit?.payload as Record<string, any> | undefined; const userName = user.email?.split('@')[0].replace(/[._-]/g, ' ') || 'there';
  const connectExtension = () => { const runtime = (window as any).chrome?.runtime; const extensionId = import.meta.env.VITE_AUDITFLUX_EXTENSION_ID as string | undefined; if (!runtime || !extensionId || !token) { setExtensionConnection('failed'); return setError('AuditFlux extension connection is unavailable. Install the extension and configure its ID for this production site.'); } runtime.sendMessage(extensionId, { type: 'auditflux:connection', apiBase: window.location.origin, accessToken: token }, (result: any) => { const state = connectionStateFromResponse(result); setExtensionConnection(state); setError(state === 'connected' ? null : 'Extension connection failed.'); }); };
  const locate = (issue: Record<string, any>) => { const runtime = (window as any).chrome?.runtime; const extensionId = import.meta.env.VITE_AUDITFLUX_EXTENSION_ID as string | undefined; setLocateNotice(null); if (!audit || !issue.locator || !runtime || !extensionId) return setError('Locate on page is unavailable until the installed AuditFlux extension is connected.'); runtime.sendMessage(extensionId, { type: 'auditflux:locate', auditId: audit.id, locator: issue.locator }, (result: any) => { if (locateSucceeded(result)) { setError(null); setLocateNotice('Located and highlighted in the audited tab.'); return; } setError(result?.reason === 'PAGE_CHANGED' ? 'The page changed after this audit. Re-scan from the extension.' : 'The audited page is no longer open.'); }); };
  const openAudit = (id?: string) => { if (!id) return; setBusy(true); setLocation(`/audit/${id}`); };
  const content = () => {
    if (busy) return <Empty title="Loading saved audit evidence…" />; if (error && !audit) return <Empty title={error} />;
    if (section === 'overview' && audit) return <Overview audit={audit} selected={selected!} history={history} userName={userName} onOpenAudit={openAudit} onConnect={connectExtension} />;
    if (!audit && section !== 'projects') return <Card className="border-primary/30 bg-[#0c1823]"><CardContent className="p-10"><h2 className="text-2xl font-bold">Your AuditFlux workspace is ready.</h2><p className="mt-2 max-w-xl text-sm text-slate-400">Run a real audit from the AuditFlux Chrome extension to populate this workspace with measured evidence.</p><div className="mt-5 flex flex-wrap gap-3"><Button onClick={connectExtension}><Wifi className="mr-2 h-4 w-4" />Connect extension</Button><Button variant="outline" onClick={() => setLocation('/projects')}><Plus className="mr-2 h-4 w-4" />Create project</Button></div></CardContent></Card>;
    if (section === 'history') return <DataTable rows={history} empty="No audit history yet. Save a real extension audit to create the first evidence point." fields={[["Captured", row => formatCaptured(row.captured_at)], ["URL", row => row.url], ["Score", row => <span className={scoreTone(row.overall_score)}>{row.overall_score ?? '—'}</span>], ["Counts", row => `${row.pass_count} pass · ${row.warn_count} warn · ${row.fail_count} fail`], ["Open", row => <Button size="sm" variant="outline" onClick={() => openAudit(row.id)}>Open audit</Button>]]} />;
    if (section === 'issues') return <DataTable rows={selected?.issues || []} empty="No saved issues for this audit." fields={[["Severity", row => <Badge className={row.severity === 'critical' ? 'bg-rose-500/20 text-rose-200' : 'bg-amber-400/15 text-amber-200'}>{row.severity}</Badge>], ["Issue", row => <button className="text-left font-medium hover:text-primary" onClick={() => setSelectedIssue(row)}>{row.title}</button>], ["Category", row => row.category], ["Evidence", row => String(row.detected || row.evidence?.[0] || '—').slice(0, 140)], ["Source", row => source(row.provenance?.source || 'CALCULATED')], ["Action", row => <Button size="sm" variant="outline" disabled={!row.locator} onClick={() => locate(row)}><LocateFixed className="mr-1 h-3.5 w-3.5" />Locate</Button>]]} />;
    if (section === 'headings') return <DataTable rows={selected?.headings || []} empty="No heading data was stored for this audit." fields={[["Level", row => `H${row.level}`], ["Heading", row => row.text || <span className="text-rose-300">Empty heading</span>], ["Question", row => row.is_question ? 'Yes' : 'No'], ["Locate", row => <Button size="sm" variant="outline" disabled={!row.locator} onClick={() => locate(row)}>Locate</Button>]]} />;
    if (section === 'links') return <DataTable rows={selected?.links || []} empty="No link data was stored for this audit." fields={[["Anchor", row => row.anchor || '—'], ["Destination", row => row.absolute_url || row.href || '—'], ["Type", row => row.link_type], ["Rel", row => row.rel || '—']]} />;
    if (section === 'images') return <DataTable rows={selected?.images || []} empty="No image data was stored for this audit." fields={[["Image", row => row.src || '—'], ["ALT", row => row.alt_missing ? <span className="text-rose-300">Missing</span> : row.alt_empty ? <span className="text-amber-300">Decorative / empty</span> : row.alt || '—'], ["Format", row => row.format || 'Unknown'], ["Status", row => row.broken ? <span className="text-rose-300">Broken</span> : 'Observed']]} />;
    if (section === 'schema') return <DataTable rows={selected?.schema || []} empty="No schema entities were stored for this audit." fields={[["Types", row => (row.types || []).join(', ') || 'None detected'], ["Valid", row => row.valid ? 'Valid' : <span className="text-rose-300">Invalid</span>], ["Evidence", row => row.error || 'JSON-LD inspected']]} />;
    if (section === 'performance') return <DataTable rows={selected?.performance || []} empty="PageSpeed data unavailable. No LAB or FIELD result has been saved for this audit." fields={[["Source", row => source(row.source)], ["Strategy", row => row.strategy], ["Performance", row => <span className={scoreTone(row.performance_score)}>{row.performance_score ?? '—'}</span>], ["Accessibility", row => <span className={scoreTone(row.accessibility_score)}>{row.accessibility_score ?? '—'}</span>], ["Best Practices", row => <span className={scoreTone(row.best_practices_score)}>{row.best_practices_score ?? '—'}</span>], ["SEO", row => <span className={scoreTone(row.seo_score)}>{row.seo_score ?? '—'}</span>]]} />;
    if (section === 'projects') return <Projects token={token!} projects={projects} refresh={refresh} />;
    if (section === 'geo' || section === 'accessibility' || section === 'technical' || section === 'resources') { const detail = payload?.detail || {}; const value = section === 'geo' ? { robots: detail.robots, sitemaps: detail.sitemaps, llms: detail.llms } : section === 'accessibility' ? detail.accessibility : section === 'technical' ? { security: detail.security, tech: detail.tech, mobile: detail.mobile } : { summary: detail.resourceSummary, largest: selected?.resources?.slice(0, 20) }; return <Card><CardHeader><CardTitle className="capitalize">{section === 'geo' ? 'GEO / AEO' : section}</CardTitle></CardHeader><CardContent><pre className="overflow-x-auto rounded-lg bg-black/20 p-4 font-mono text-xs leading-6 text-slate-300">{JSON.stringify(value, null, 2)}</pre></CardContent></Card>; }
    if (section === 'reports') return <Empty title="Reports use the same persisted audit data. Browser Print / Save PDF is available from this audit view; server-side PDF export is not configured yet." />;
    if (section === 'settings') return <Card><CardHeader><CardTitle>Account & integration</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-slate-400">The production API is the same Vercel origin serving this dashboard. PageSpeed and CrUX keys remain server-side; the extension never receives them.</p><Button onClick={connectExtension}><Wifi className="mr-2 h-4 w-4" />Connect extension</Button><p className="rounded-md border border-amber-300/20 bg-amber-300/10 p-3 text-sm text-amber-100"><strong>SECURITY WARNING:</strong> no raw API key is stored in this dashboard or submitted with audit payloads.</p></CardContent></Card>;
    return <Empty title="This AuditFlux area is not connected yet." />;
  };
  const title = section === 'overview' ? 'Audit evidence' : section.replace('-', ' '); return <DashboardLayout><header className="af-page-header"><div><p className="af-kicker">AuditFlux / {section}</p><h1 className="af-page-title">{title}</h1><p className="af-page-subtitle">{audit ? audit.url : 'Real audit data appears after the extension saves a scan.'}</p></div><div className="af-header-actions">{extensionConnection === 'connected' && <Badge className="border border-emerald-300/25 bg-emerald-300/10 text-emerald-200">Extension connected</Badge>}<Button variant="outline" onClick={() => { setBusy(true); void refresh(); }}><RefreshCw className="mr-2 h-4 w-4" />Refresh</Button>{audit && <Button variant="outline" onClick={() => window.print()}>Print / Save PDF</Button>}</div></header>{error && <div className="mb-5 flex gap-2 rounded-lg border border-amber-300/25 bg-amber-300/[.08] p-3 text-sm text-amber-100"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div>}{locateNotice && <div className="mb-5 rounded-lg border border-emerald-300/25 bg-emerald-300/[.08] p-3 text-sm text-emerald-200">{locateNotice}</div>}{content()}{selectedIssue && <div className="fixed inset-0 z-50 flex justify-end bg-black/55" onClick={() => setSelectedIssue(null)}><aside className="h-full w-full max-w-xl overflow-y-auto bg-[#0c1823] p-6 shadow-2xl" onClick={event => event.stopPropagation()}><div className="flex justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-wider text-primary">{selectedIssue.severity}</p><h2 className="mt-2 text-xl font-semibold">{selectedIssue.title}</h2></div><Button variant="ghost" onClick={() => setSelectedIssue(null)}>Close</Button></div><dl className="mt-6 space-y-5 text-sm"><div><dt className="font-medium">What we found</dt><dd className="mt-1 text-slate-400">{selectedIssue.detected || 'No additional detected text was stored.'}</dd></div><div><dt className="font-medium">Why it matters</dt><dd className="mt-1 text-slate-400">{selectedIssue.why || 'No explanation was stored.'}</dd></div><div><dt className="font-medium">Recommendation</dt><dd className="mt-1 text-slate-400">{selectedIssue.recommendation || 'No recommendation was stored.'}</dd></div><div><dt className="font-medium">Evidence</dt><dd className="mt-1 whitespace-pre-wrap text-slate-400">{JSON.stringify(selectedIssue.evidence || [], null, 2)}</dd></div></dl><div className="mt-7 flex gap-3"><Button disabled={!selectedIssue.locator} onClick={() => locate(selectedIssue)}><LocateFixed className="mr-2 h-4 w-4" />Locate on page</Button><Button variant="outline" onClick={() => navigator.clipboard.writeText(selectedIssue.recommendation || '')}>Copy recommendation</Button></div></aside></div>}</DashboardLayout>;
}

function Projects({ token, projects, refresh }: { token: string; projects: Record<string, any>[]; refresh: () => Promise<void> }) { const [name, setName] = useState(''); const [url, setUrl] = useState(''); const [error, setError] = useState<string | null>(null); async function submit(event: FormEvent) { event.preventDefault(); try { await auditApi.createProject(token, { name, primaryUrl: url }); setName(''); setUrl(''); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Project could not be created.'); } } return <div className="space-y-5"><Card className="border-primary/30 bg-[#0c1823]"><CardContent className="p-5"><form onSubmit={submit} className="grid gap-3 lg:grid-cols-[1fr_1.7fr_auto]"><Input required placeholder="Project name" value={name} onChange={event => setName(event.target.value)} /><Input required type="url" placeholder="https://example.com" value={url} onChange={event => setUrl(event.target.value)} /><Button type="submit"><Plus className="mr-2 h-4 w-4" />Create project</Button></form>{error && <p className="mt-3 text-sm text-rose-300">{error}</p>}</CardContent></Card>{projects.length ? <div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{projects.map(project => <Card key={project.id}><CardContent className="p-5"><p className="font-medium">{project.name}</p><a className="mt-2 flex items-center gap-1 text-sm text-primary hover:underline" href={project.primary_url} target="_blank" rel="noreferrer">{project.primary_url}<ExternalLink className="h-3 w-3" /></a><p className="mt-4 text-xs text-slate-500">{Array.isArray(project.urls) ? project.urls.length : 1} tracked URL(s)</p></CardContent></Card>)}</div> : <Empty title="No projects yet. Create one here, or save an extension audit and AuditFlux will create a project from the audited website." />}</div>; }
