import DashboardLayout from '@/components/DashboardLayout';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { useSupabaseAuth } from '@/contexts/SupabaseAuthContext';
import { auditApi, SavedAudit } from '@/lib/audit-api';
import { auditIdFromLocation, routeSection, type AuditSection } from '@/lib/audit-view';
import { connectionStateFromResponse, locateSucceeded, type ExtensionConnectionState } from '@/lib/extension-bridge';
import { AlertTriangle, CheckCircle2, ExternalLink, Loader2, LocateFixed, LogIn, Plus, RefreshCw, Wifi } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { useLocation } from 'wouter';

const scoreTone = (score?: number | null) => score == null ? 'text-slate-500' : score >= 80 ? 'text-primary' : score >= 50 ? 'text-amber-300' : 'text-rose-300';
const source = (value: string) => <Badge variant="outline" className="font-mono text-[10px] tracking-wider">{value}</Badge>;

function SignIn() {
  const { configured, signIn, signUp } = useSupabaseAuth();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState<string | null>(null); const [working, setWorking] = useState(false);
  async function submit(event: FormEvent, mode: 'in' | 'up') { event.preventDefault(); setWorking(true); setError(mode === 'in' ? await signIn(email, password) : await signUp(email, password)); setWorking(false); }
  return <main className="grid min-h-screen place-items-center bg-[#07111f] p-5 text-slate-100"><Card className="w-full max-w-md border-white/[.09] bg-[#0b1a2b]"><CardHeader><CardTitle>Sign in to AuditFlux</CardTitle><p className="text-sm text-muted-foreground">Use your AuditFlux Supabase account to access saved evidence.</p></CardHeader><CardContent>{!configured ? <p className="rounded-md border border-amber-300/30 bg-amber-300/10 p-3 text-sm text-amber-100">Supabase client configuration is required before production sign-in can be used.</p> : <form className="space-y-3"><Input type="email" required placeholder="you@example.com" value={email} onChange={event => setEmail(event.target.value)} /><Input type="password" required minLength={6} placeholder="Password" value={password} onChange={event => setPassword(event.target.value)} />{error && <p className="text-sm text-rose-300">{error}</p>}<div className="grid grid-cols-2 gap-3"><Button disabled={working} onClick={event => void submit(event, 'in')}><LogIn className="mr-2 h-4 w-4" /> Sign in</Button><Button type="button" variant="outline" disabled={working} onClick={event => void submit(event, 'up')}>Create account</Button></div></form>}</CardContent></Card></main>;
}

function DataTable({ rows, fields, empty }: { rows: Record<string, any>[]; fields: [string, (row: Record<string, any>) => React.ReactNode][]; empty: string }) { return rows.length ? <div className="overflow-x-auto rounded-xl border border-white/[.08]"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-white/[.035] text-xs uppercase tracking-wider text-slate-400"><tr>{fields.map(([label]) => <th key={label} className="px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row.id || index} className="border-t border-white/[.06] hover:bg-white/[.025]">{fields.map(([label, render]) => <td key={label} className="px-4 py-3 align-top">{render(row)}</td>)}</tr>)}</tbody></table></div> : <Empty title={empty} />; }
function Empty({ title }: { title: string }) { return <Card className="border-dashed border-white/[.12] bg-transparent"><CardContent className="p-10 text-center text-sm text-slate-400">{title}</CardContent></Card>; }
function Metric({ label, value, tone }: { label: string; value: React.ReactNode; tone?: string }) { return <div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-slate-500">{label}</p><p className={`mt-1 font-mono text-2xl font-semibold ${tone || 'text-slate-100'}`}>{value}</p></div>; }

export default function Home() {
  const { user, session, loading } = useSupabaseAuth();
  const [location, setLocation] = useLocation();
  const [history, setHistory] = useState<Record<string, any>[]>([]); const [projects, setProjects] = useState<Record<string, any>[]>([]); const [selected, setSelected] = useState<SavedAudit | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(true); const [selectedIssue, setSelectedIssue] = useState<Record<string, any> | null>(null); const [extensionConnection, setExtensionConnection] = useState<ExtensionConnectionState>('unknown'); const [locateNotice, setLocateNotice] = useState<string | null>(null);
  const token = session?.access_token;
  const selectedId = auditIdFromLocation(location) || selected?.audit?.id;
  const refresh = useCallback(async () => { if (!token) return; try { const [historyResult, projectResult] = await Promise.all([auditApi.history(token), auditApi.projects(token)]); setHistory(historyResult.audits); setProjects(projectResult.projects); const target = selectedId || historyResult.audits[0]?.id; if (target) setSelected(await auditApi.audit(token, target)); else setSelected(null); setError(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load saved audits.'); } finally { setBusy(false); } }, [token, selectedId]);
  useEffect(() => { void refresh(); }, [refresh]);
  useEffect(() => { if (!token) return; const timer = window.setInterval(() => void refresh(), 15000); return () => window.clearInterval(timer); }, [token, refresh]);
  if (loading) return <main className="grid min-h-screen place-items-center bg-[#07111f]"><Loader2 className="animate-spin text-primary" /></main>;
  if (!user) return <SignIn />;
  const section = routeSection(location); const audit = selected?.audit; const payload = audit?.payload as Record<string, any> | undefined;
  const connectExtension = () => { const chromeRuntime = (window as any).chrome?.runtime; const extensionId = import.meta.env.VITE_AUDITFLUX_EXTENSION_ID as string | undefined; if (!chromeRuntime || !extensionId || !token) { setExtensionConnection('failed'); return setError('AuditFlux extension connection is unavailable. Install the extension and configure its ID for this production site.'); } chromeRuntime.sendMessage(extensionId, { type: 'auditflux:connection', apiBase: window.location.origin, accessToken: token }, (result: any) => { const state = connectionStateFromResponse(result); setExtensionConnection(state); setError(state === 'connected' ? null : 'Extension connection failed.'); }); };
  const locate = (issue: Record<string, any>) => { const chromeRuntime = (window as any).chrome?.runtime; const extensionId = import.meta.env.VITE_AUDITFLUX_EXTENSION_ID as string | undefined; setLocateNotice(null); if (!audit || !issue.locator || !chromeRuntime || !extensionId) return setError('Locate on page is unavailable until the installed AuditFlux extension is connected.'); chromeRuntime.sendMessage(extensionId, { type: 'auditflux:locate', auditId: audit.id, locator: issue.locator }, (result: any) => { if (locateSucceeded(result)) { setError(null); setLocateNotice('Located and highlighted in the audited tab.'); return; } setError(result?.reason === 'PAGE_CHANGED' ? 'The page changed after this audit. Re-scan from the extension.' : 'The audited page is no longer open.'); }); };
  const content = () => {
    if (busy) return <Empty title="Loading saved audit evidence…" />;
    if (error && !audit) return <Empty title={error} />;
    if (section === 'history') return <DataTable rows={history} empty="No audit history yet. Save a real extension audit to create the first evidence point." fields={[["Captured", row => new Date(row.captured_at).toLocaleString()], ["URL", row => row.url], ["Score", row => <span className={scoreTone(row.overall_score)}>{row.overall_score ?? '—'}</span>], ["Counts", row => `${row.pass_count} pass · ${row.warn_count} warn · ${row.fail_count} fail`], ["Open", row => <Button size="sm" variant="outline" onClick={() => { setBusy(true); setLocation('/audit/' + row.id); }}>Open audit</Button>]]} />;
    if (!audit && section !== 'projects') return <Card className="border-primary/25 bg-primary/[.045]"><CardContent className="p-10"><h1 className="text-2xl font-semibold">Your AuditFlux workspace is ready.</h1><p className="mt-2 max-w-xl text-sm text-slate-400">Run an audit from the AuditFlux Chrome extension to populate this dashboard with measured evidence.</p><div className="mt-5 flex flex-wrap gap-3"><Button onClick={connectExtension}><Wifi className="mr-2 h-4 w-4" />Connect Extension</Button><Button variant="outline" onClick={() => setLocation('/projects')}><Plus className="mr-2 h-4 w-4" />Create Project</Button></div></CardContent></Card>;
    if (section === 'overview' && audit) return <div className="grid gap-5 xl:grid-cols-[1.1fr_2fr]"><Card className="border-primary/25 bg-primary/[.04]"><CardContent className="p-6"><p className="font-mono text-[11px] uppercase tracking-[.18em] text-primary">Real audit score</p><p className={`mt-2 font-mono text-7xl font-bold ${scoreTone(audit.overall_score)}`}>{audit.overall_score ?? '—'}</p><p className="mt-2 text-sm text-slate-400">Captured {new Date(audit.captured_at).toLocaleString()}</p><div className="mt-6 grid grid-cols-2 gap-5"><Metric label="Applicable" value={`${audit.coverage_applicable}/${audit.coverage_total}`} /><Metric label="Pass" value={audit.pass_count} tone="text-primary" /><Metric label="Warnings" value={audit.warn_count} tone="text-amber-300" /><Metric label="Critical" value={audit.critical_count} tone="text-rose-300" /></div></CardContent></Card><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{selected?.categories.map(category => <Card key={category.id} className="border-white/[.08] bg-card/70"><CardContent className="p-5"><div className="flex justify-between gap-4"><p className="font-medium">{category.label}</p><span className={`font-mono text-2xl ${scoreTone(category.score)}`}>{category.score ?? 'N/A'}</span></div><p className="mt-3 text-sm text-slate-400">{category.passed} of {category.checks} applicable checks passed</p>{source(category.source)}</CardContent></Card>)}</div></div>;
    if (section === 'issues') return <DataTable rows={selected?.issues || []} empty="No saved issues for this audit." fields={[["Severity", row => <Badge className={row.severity === 'critical' ? 'bg-rose-500/20 text-rose-200' : 'bg-amber-400/15 text-amber-200'}>{row.severity}</Badge>], ["Issue", row => <button className="text-left font-medium hover:text-primary" onClick={() => setSelectedIssue(row)}>{row.title}</button>], ["Category", row => row.category], ["Evidence", row => String(row.detected || row.evidence?.[0] || '—').slice(0, 140)], ["Source", row => source(row.provenance?.source || 'CALCULATED')], ["Action", row => <Button size="sm" variant="outline" disabled={!row.locator} onClick={() => locate(row)}><LocateFixed className="mr-1 h-3.5 w-3.5" />Locate</Button>]]} />;
    if (section === 'headings') return <DataTable rows={selected?.headings || []} empty="No heading data was stored for this audit." fields={[["Level", row => `H${row.level}`], ["Heading", row => row.text || <span className="text-rose-300">Empty heading</span>], ["Question", row => row.is_question ? 'Yes' : 'No'], ["Locate", row => <Button size="sm" variant="outline" disabled={!row.locator} onClick={() => locate(row)}>Locate</Button>]]} />;
    if (section === 'links') return <DataTable rows={selected?.links || []} empty="No link data was stored for this audit." fields={[["Anchor", row => row.anchor || '—'], ["Destination", row => row.absolute_url || row.href || '—'], ["Type", row => row.link_type], ["Rel", row => row.rel || '—']]} />;
    if (section === 'images') return <DataTable rows={selected?.images || []} empty="No image data was stored for this audit." fields={[["Image", row => row.src || '—'], ["ALT", row => row.alt_missing ? <span className="text-rose-300">Missing</span> : row.alt_empty ? <span className="text-amber-300">Decorative / empty</span> : row.alt || '—'], ["Format", row => row.format || 'Unknown'], ["Status", row => row.broken ? <span className="text-rose-300">Broken</span> : 'Observed']]} />;
    if (section === 'schema') return <DataTable rows={selected?.schema || []} empty="No schema entities were stored for this audit." fields={[["Types", row => (row.types || []).join(', ') || 'None detected'], ["Valid", row => row.valid ? 'Valid' : <span className="text-rose-300">Invalid</span>], ["Evidence", row => row.error || 'JSON-LD inspected']]} />;
    if (section === 'performance') return <DataTable rows={selected?.performance || []} empty="PageSpeed data unavailable. No LAB or FIELD result has been saved for this audit." fields={[["Source", row => source(row.source)], ["Strategy", row => row.strategy], ["Performance", row => <span className={scoreTone(row.performance_score)}>{row.performance_score ?? '—'}</span>], ["Accessibility", row => <span className={scoreTone(row.accessibility_score)}>{row.accessibility_score ?? '—'}</span>], ["Best Practices", row => <span className={scoreTone(row.best_practices_score)}>{row.best_practices_score ?? '—'}</span>], ["SEO", row => <span className={scoreTone(row.seo_score)}>{row.seo_score ?? '—'}</span>]]} />;
    if (section === 'projects') return <Projects token={token!} projects={projects} refresh={refresh} />;
    if (section === 'geo' || section === 'accessibility' || section === 'technical' || section === 'resources') { const detail = payload?.detail || {}; const value = section === 'geo' ? { robots: detail.robots, sitemaps: detail.sitemaps, llms: detail.llms } : section === 'accessibility' ? detail.accessibility : section === 'technical' ? { security: detail.security, tech: detail.tech, mobile: detail.mobile } : { summary: detail.resourceSummary, largest: selected?.resources?.slice(0, 20) }; return <Card><CardHeader><CardTitle className="capitalize">{section === 'geo' ? 'GEO / AEO' : section}</CardTitle></CardHeader><CardContent><pre className="overflow-x-auto rounded-lg bg-black/20 p-4 font-mono text-xs leading-6 text-slate-300">{JSON.stringify(value, null, 2)}</pre></CardContent></Card>; }
    if (section === 'reports') return <Empty title="Reports use the same persisted audit data. Browser Print / Save PDF is available from this audit view; server-side PDF export is not configured yet." />;
    if (section === 'settings') return <Card><CardHeader><CardTitle>Account & integration</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-slate-400">The production API is the same Vercel origin serving this dashboard. PageSpeed and CrUX keys remain server-side; the extension never receives them.</p><Button onClick={connectExtension}><Wifi className="mr-2 h-4 w-4" />Connect Extension</Button><p className="rounded-md border border-amber-300/20 bg-amber-300/10 p-3 text-sm text-amber-100"><strong>SECURITY WARNING:</strong> no raw API key is stored in this dashboard or submitted with audit payloads.</p></CardContent></Card>;
    return <Empty title="This AuditFlux area is not connected yet." />;
  };
  return <DashboardLayout><header className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-[11px] uppercase tracking-[.22em] text-primary">AuditFlux / {section}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{section === 'overview' ? 'Audit evidence' : section.replace('-', ' ')}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{audit ? audit.url : 'Real audit data appears after the extension saves a scan.'}</p></div><div className="flex flex-wrap items-center gap-2">{extensionConnection === 'connected' && <Badge className="border border-primary/30 bg-primary/15 text-primary">Extension connected</Badge>}<Button variant="outline" onClick={() => { setBusy(true); void refresh(); }}><RefreshCw className="mr-2 h-4 w-4" />Refresh</Button>{audit && <Button variant="outline" onClick={() => window.print()}>Print / Save PDF</Button>}</div></header>{error && <div className="mb-5 flex gap-2 rounded-lg border border-amber-300/25 bg-amber-300/[.08] p-3 text-sm text-amber-100"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div>}{locateNotice && <div className="mb-5 rounded-lg border border-primary/25 bg-primary/[.08] p-3 text-sm text-primary">{locateNotice}</div>}{content()}{selectedIssue && <div className="fixed inset-0 z-50 flex justify-end bg-black/50" onClick={() => setSelectedIssue(null)}><aside className="h-full w-full max-w-xl overflow-y-auto bg-[#0b1a2b] p-6 shadow-2xl" onClick={event => event.stopPropagation()}><div className="flex justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-wider text-primary">{selectedIssue.severity}</p><h2 className="mt-2 text-xl font-semibold">{selectedIssue.title}</h2></div><Button variant="ghost" onClick={() => setSelectedIssue(null)}>Close</Button></div><dl className="mt-6 space-y-5 text-sm"><div><dt className="font-medium">What we found</dt><dd className="mt-1 text-slate-400">{selectedIssue.detected || 'No additional detected text was stored.'}</dd></div><div><dt className="font-medium">Why it matters</dt><dd className="mt-1 text-slate-400">{selectedIssue.why || 'No explanation was stored.'}</dd></div><div><dt className="font-medium">Recommendation</dt><dd className="mt-1 text-slate-400">{selectedIssue.recommendation || 'No recommendation was stored.'}</dd></div><div><dt className="font-medium">Evidence</dt><dd className="mt-1 whitespace-pre-wrap text-slate-400">{JSON.stringify(selectedIssue.evidence || [], null, 2)}</dd></div></dl><div className="mt-7 flex gap-3"><Button disabled={!selectedIssue.locator} onClick={() => locate(selectedIssue)}><LocateFixed className="mr-2 h-4 w-4" />Locate on page</Button><Button variant="outline" onClick={() => navigator.clipboard.writeText(selectedIssue.recommendation || '')}>Copy recommendation</Button></div></aside></div>}</DashboardLayout>;
}

function Projects({ token, projects, refresh }: { token: string; projects: Record<string, any>[]; refresh: () => Promise<void> }) { const [name, setName] = useState(''); const [url, setUrl] = useState(''); const [error, setError] = useState<string | null>(null); async function submit(event: FormEvent) { event.preventDefault(); try { await auditApi.createProject(token, { name, primaryUrl: url }); setName(''); setUrl(''); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Project could not be created.'); } } return <div className="space-y-5"><Card className="border-primary/25 bg-primary/[.04]"><CardContent className="p-5"><form onSubmit={submit} className="grid gap-3 lg:grid-cols-[1fr_1.7fr_auto]"><Input required placeholder="Project name" value={name} onChange={event => setName(event.target.value)} /><Input required type="url" placeholder="https://example.com" value={url} onChange={event => setUrl(event.target.value)} /><Button type="submit"><Plus className="mr-2 h-4 w-4" />Create project</Button></form>{error && <p className="mt-3 text-sm text-rose-300">{error}</p>}</CardContent></Card>{projects.length ? <div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{projects.map(project => <Card key={project.id}><CardContent className="p-5"><p className="font-medium">{project.name}</p><a className="mt-2 flex items-center gap-1 text-sm text-primary hover:underline" href={project.primary_url} target="_blank" rel="noreferrer">{project.primary_url}<ExternalLink className="h-3 w-3" /></a><p className="mt-4 text-xs text-slate-500">{Array.isArray(project.urls) ? project.urls.length : 1} tracked URL(s)</p></CardContent></Card>)}</div> : <Empty title="No projects yet. Create one here, or save an extension audit and AuditFlux will create a project from the audited website." />}</div>; }
