import DashboardLayout from '@/components/DashboardLayout';
import UnifiedAuditSection from '@/components/UnifiedAuditSection';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { useSupabaseAuth } from '@/contexts/SupabaseAuthContext';
import { auditApi, type SavedAudit } from '@/lib/audit-api';
import { auditIdFromLocation, auditPath, routeSection, type AuditSection } from '@/lib/audit-view';
import { connectionStateFromResponse, locateSucceeded, overlayToggled, rescanSucceeded, type ExtensionConnectionState } from '@/lib/extension-bridge';
import { AlertTriangle, CheckCircle2, ExternalLink, Loader2, LogIn, Plus, Radar, RefreshCw, Wifi } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { useLocation } from 'wouter';

function SignIn() {
  const { configured, signIn, signUp } = useSupabaseAuth();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState<string | null>(null); const [working, setWorking] = useState(false);
  async function submit(event: FormEvent, mode: 'in' | 'up') { event.preventDefault(); setWorking(true); setError(mode === 'in' ? await signIn(email, password) : await signUp(email, password)); setWorking(false); }
  return <main className="grid min-h-screen place-items-center bg-background p-5 text-foreground"><Card className="w-full max-w-md border-white/[.12] bg-[#0c1823] shadow-2xl"><CardHeader><CardTitle className="text-2xl">Sign In To AuditFlux</CardTitle><p className="text-sm text-muted-foreground">Use your AuditFlux Supabase account to access saved evidence.</p></CardHeader><CardContent>{!configured ? <p className="rounded-md border border-amber-300/30 bg-amber-300/10 p-3 text-sm text-amber-100">Supabase client configuration is required before production sign-in can be used.</p> : <form className="space-y-3"><Input type="email" required placeholder="you@example.com" value={email} onChange={event => setEmail(event.target.value)} /><Input type="password" required minLength={6} placeholder="Password" value={password} onChange={event => setPassword(event.target.value)} />{error && <p className="text-sm text-rose-300">{error}</p>}<div className="grid grid-cols-2 gap-3"><Button disabled={working} onClick={event => void submit(event, 'in')}><LogIn className="mr-2 h-4 w-4" />Sign In</Button><Button type="button" variant="outline" disabled={working} onClick={event => void submit(event, 'up')}>Create Account</Button></div></form>}</CardContent></Card></main>;
}

function RadarLoader({ detail = 'Loading The Current Saved Audit' }: { detail?: string }) {
  return <div className="grid min-h-[420px] place-items-center"><div className="text-center"><div className="relative mx-auto grid h-40 w-40 place-items-center rounded-full border border-primary/30 bg-[radial-gradient(circle,#1b4666_0%,#0c1823_48%,transparent_50%)] shadow-[0_0_55px_rgba(60,180,255,.16)]"><i className="absolute inset-3 rounded-full border border-primary/25" /><i className="absolute inset-9 rounded-full border border-primary/20" /><i className="af-radar-sweep absolute inset-0 rounded-full" /><Radar className="relative h-9 w-9 text-primary" /></div><p className="mt-6 text-lg font-semibold text-white">AuditFlux</p><p className="mt-1 text-sm text-slate-400">{detail}</p><p className="mt-2 text-xs text-slate-500">This operation retrieves saved evidence. It does not start a new browser scan.</p></div></div>;
}

function Projects({ token, projects, refresh }: { token: string; projects: Record<string, any>[]; refresh: () => Promise<void> }) {
  const [name, setName] = useState(''); const [url, setUrl] = useState(''); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); try { await auditApi.createProject(token, { name, primaryUrl: url }); setName(''); setUrl(''); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Project could not be created.'); } }
  return <div className="space-y-5"><div><p className="af-kicker">Workspace</p><h2 className="af-page-title">Projects</h2><p className="af-page-subtitle">Projects group saved AuditFlux evidence without changing the source audit record.</p></div><Card className="border-primary/30 bg-[#0c1823]"><CardContent className="p-5"><form onSubmit={submit} className="grid gap-3 lg:grid-cols-[1fr_1.7fr_auto]"><Input required placeholder="Project Name" value={name} onChange={event => setName(event.target.value)} /><Input required type="url" placeholder="https://example.com" value={url} onChange={event => setUrl(event.target.value)} /><Button type="submit"><Plus className="mr-2 h-4 w-4" />Create Project</Button></form>{error && <p className="mt-3 text-sm text-rose-300">{error}</p>}</CardContent></Card>{projects.length ? <div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{projects.map(project => <Card key={project.id}><CardContent className="p-5"><p className="font-medium">{project.name}</p><a className="mt-2 flex items-center gap-1 text-sm text-primary hover:underline" href={project.primary_url} target="_blank" rel="noreferrer">{project.primary_url}<ExternalLink className="h-3 w-3" /></a><p className="mt-4 text-xs text-slate-500">{Array.isArray(project.urls) ? project.urls.length : 1} tracked URL(s)</p></CardContent></Card>)}</div> : <Card className="border-dashed border-white/[.16] bg-[#0c1823]/70"><CardContent className="p-10 text-center text-sm text-slate-400">No projects yet. Create one here, or save an extension audit and AuditFlux will create a project from the audited website.</CardContent></Card>}</div>;
}

export default function UnifiedHome() {
  const { user, session, loading } = useSupabaseAuth(); const [location, setLocation] = useLocation();
  const [history, setHistory] = useState<Record<string, any>[]>([]); const [projects, setProjects] = useState<Record<string, any>[]>([]); const [selected, setSelected] = useState<SavedAudit | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(true); const [extensionConnection, setExtensionConnection] = useState<ExtensionConnectionState>('unknown'); const [locateNotice, setLocateNotice] = useState<string | null>(null);
  const token = session?.access_token; const routeAuditId = auditIdFromLocation(location);
  const refresh = useCallback(async (showLoader = false) => { if (!token) return; if (showLoader) setBusy(true); try { const [historyResult, projectResult] = await Promise.all([auditApi.history(token), auditApi.projects(token)]); setHistory(historyResult.audits); setProjects(projectResult.projects); const target = routeAuditId; setSelected(target ? await auditApi.audit(token, target) : null); setError(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load saved audits.'); } finally { setBusy(false); } }, [token, routeAuditId]);
  useEffect(() => { void refresh(true); }, [refresh]);
  useEffect(() => { if (!token) return; const timer = window.setInterval(() => void refresh(false), 15000); return () => window.clearInterval(timer); }, [token, refresh]);
  if (loading) return <main className="grid min-h-screen place-items-center bg-background"><Loader2 className="animate-spin text-primary" /></main>;
  if (!user) return <SignIn />;
  const section = routeSection(location); const audit = selected?.audit as Record<string, any> | undefined;
  const connectExtension = () => { const runtime = (window as any).chrome?.runtime; const extensionId = import.meta.env.VITE_AUDITFLUX_EXTENSION_ID as string | undefined; if (!runtime || !extensionId || !token) { setExtensionConnection('failed'); setError('AuditFlux extension connection is unavailable. Install the extension and configure its ID for this production site.'); return; } runtime.sendMessage(extensionId, { type: 'auditflux:connection', apiBase: window.location.origin, accessToken: token }, (result: any) => { const bridgeError = runtime.lastError?.message; const state = bridgeError ? 'failed' : connectionStateFromResponse(result); setExtensionConnection(state); setError(state === 'connected' ? null : bridgeError ? `Extension connection failed: ${bridgeError}` : 'Extension connection failed.'); }); };
  const locate = (item: Record<string, unknown>) => { const runtime = (window as any).chrome?.runtime; const extensionId = import.meta.env.VITE_AUDITFLUX_EXTENSION_ID as string | undefined; setLocateNotice(null); if (!audit || !item.locator || !runtime || !extensionId) { setError('Locate On Page is unavailable until the installed AuditFlux extension is connected and the audit contains a saved locator.'); return; } runtime.sendMessage(extensionId, { type: 'auditflux:locate', auditId: audit.id, locator: item.locator }, (result: any) => { if (locateSucceeded(result)) { setError(null); setLocateNotice('Located and highlighted in the audited tab.'); return; } setError(result?.reason === 'PAGE_CHANGED' ? 'The page changed after this audit. Re-scan from the extension.' : 'The audited page is no longer open.'); }); };
  const toggleOverlay = () => { const runtime = (window as any).chrome?.runtime; const extensionId = import.meta.env.VITE_AUDITFLUX_EXTENSION_ID as string | undefined; if (!audit || !runtime || !extensionId) { setError('View H1–H6 On Page is unavailable until the AuditFlux extension is connected.'); return; } runtime.sendMessage(extensionId, { type: 'auditflux:toggle-heading-overlay', auditId: audit.id }, (result: any) => { if (overlayToggled(result)) { setError(null); setLocateNotice(result.enabled ? `H1–H6 overlay enabled for ${result.count ?? 'saved'} headings.` : 'H1–H6 overlay removed from the audited page.'); return; } setError(result?.reason === 'PAGE_CHANGED' ? 'The page changed after this audit. Re-scan from the extension.' : 'The extension could not change the heading overlay.'); }); };
  const rescan = () => { const runtime = (window as any).chrome?.runtime; const extensionId = import.meta.env.VITE_AUDITFLUX_EXTENSION_ID as string | undefined; if (!audit || !runtime || !extensionId) { setError('Re-Scan is unavailable until the AuditFlux extension is connected.'); return; } setBusy(true); runtime.sendMessage(extensionId, { type: 'auditflux:rescan', auditId: audit.id }, (result: any) => { if (rescanSucceeded(result)) { setLocateNotice(result.duplicate ? 'The page did not change; AuditFlux reused the existing audit record.' : 'A fresh audit was saved.'); setLocation(auditPath(result.auditId, 'overview')); return; } setBusy(false); setError(result?.reason === 'PAGE_CHANGED' ? 'The page changed after this audit. Open the extension on the current page and run a new audit.' : result?.error || 'The extension could not complete a new audit.'); }); };
  const openAudit = (id?: string, destination: AuditSection = 'overview') => { if (!id) return; setLocation(auditPath(id, destination)); };
  const context = audit ? <div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 bg-[#0c1823]/70 px-4 py-3"><div className="min-w-0"><p className="truncate text-sm font-medium text-white">{audit.url}</p><p className="mt-1 text-xs text-slate-400">Saved audit · {audit.captured_at ? new Date(audit.captured_at).toLocaleString() : 'Capture time unavailable'}</p></div><div className="flex flex-wrap gap-2">{extensionConnection === 'connected' && <Badge className="border border-emerald-300/25 bg-emerald-300/10 text-emerald-200">Extension Connected</Badge>}<Button size="sm" variant="outline" onClick={() => window.open(String(audit.url), '_blank', 'noopener,noreferrer')}>Open Page</Button><Button size="sm" variant="outline" onClick={() => void refresh(true)}><RefreshCw className="mr-1.5 h-3.5 w-3.5" />Refresh</Button><Button size="sm" variant="outline" onClick={rescan}><Radar className="mr-1.5 h-3.5 w-3.5" />Re-Scan</Button><Button size="sm" variant="outline" onClick={() => setLocation(auditPath(String(audit.id), 'reports'))}>Export</Button></div></div> : null;
  let content: React.ReactNode;
  if (busy) content = <RadarLoader />;
  else if (section === 'projects') content = <Projects token={token!} projects={projects} refresh={() => refresh(false)} />;
  else if (section === 'history') content = <div className="space-y-4"><div><p className="af-kicker">Workspace</p><h2 className="af-page-title">Audit History</h2><p className="af-page-subtitle">Every saved scan remains a distinct audit record.</p></div>{history.length ? <div className="overflow-x-auto rounded-xl border border-white/10 bg-[#0c1823]/70"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-white/10 bg-white/[.03] text-xs uppercase tracking-wide text-slate-400"><tr><th className="p-3">Captured</th><th className="p-3">URL</th><th className="p-3">Score</th><th className="p-3">Coverage</th><th className="p-3" /></tr></thead><tbody>{history.map(row => <tr key={row.id} className="border-b border-white/[.06]"><td className="p-3 text-slate-400">{row.captured_at ? new Date(row.captured_at).toLocaleString() : 'Not Captured'}</td><td className="max-w-96 truncate p-3 text-white">{row.url}</td><td className="p-3 text-white">{row.overall_score ?? '—'}</td><td className="p-3 text-slate-400">{row.pass_count ?? 0} passed / {row.coverage_applicable ?? 0}</td><td className="p-3"><Button size="sm" variant="outline" onClick={() => openAudit(row.id)}>Open Audit</Button></td></tr>)}</tbody></table></div> : <Card className="border-dashed border-white/[.16] bg-[#0c1823]/70"><CardContent className="p-10 text-center text-sm text-slate-400">No audit history yet. Save a real extension audit to create the first evidence point.</CardContent></Card>}</div>;
  else if (section === 'settings') content = <Card className="border-white/10 bg-[#0c1823]/80"><CardHeader><CardTitle>Account And Integration</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-slate-400">The production API is the same Vercel origin serving this workspace. PageSpeed and CrUX keys remain server-side; the extension never receives them.</p><Button onClick={connectExtension}><Wifi className="mr-2 h-4 w-4" />Connect Extension</Button></CardContent></Card>;
  else if (!selected) content = <Card className="border-primary/30 bg-[#0c1823]"><CardContent className="p-10"><p className="af-kicker">Workspace</p><h2 className="text-2xl font-bold">Choose An Audit To Review.</h2><p className="mt-2 max-w-xl text-sm text-slate-400">No audit was supplied to this Web App session, so AuditFlux has not loaded a prior saved report. Open an audit from history or run a new real audit through the extension.</p><div className="mt-5 flex flex-wrap gap-3"><Button onClick={() => setLocation('/history')}>Open Audit History</Button><Button variant="outline" onClick={connectExtension}>{extensionConnection === 'connected' ? <><CheckCircle2 className="mr-2 h-4 w-4 text-emerald-300" />Extension Connected</> : <><Wifi className="mr-2 h-4 w-4" />Connect Extension</>}</Button><Button variant="outline" onClick={() => setLocation('/projects')}><Plus className="mr-2 h-4 w-4" />Create Project</Button></div></CardContent></Card>;
  else content = <UnifiedAuditSection section={section} selected={selected} onLocate={locate} onOverlay={toggleOverlay} onOpenAudit={openAudit} onConnect={connectExtension} />;
  return <DashboardLayout>{context}{error && <div className="mb-5 flex gap-2 rounded-lg border border-amber-300/25 bg-amber-300/[.08] p-3 text-sm text-amber-100"><AlertTriangle className="h-4 w-4 shrink-0" />{error}</div>}{locateNotice && <div className="mb-5 rounded-lg border border-emerald-300/25 bg-emerald-300/[.08] p-3 text-sm text-emerald-200">{locateNotice}</div>}{content}</DashboardLayout>;
}
