import { describe, expect, it } from 'vitest';
import { excelExportData, exportCsvSets, exportFileBase, exportReadiness, normalizedAuditReport, standaloneHtml } from './audit-export';

const saved: any = { audit: { id: 'aud_123', url: 'https://example.com/page', captured_at: '2026-08-23T10:26:00.000Z', overall_score: 72, coverage_applicable: 7, pass_count: 4, critical_count: 1, warn_count: 1, notice_count: 1, na_count: 2, payload: { detail: { pageEssentials: { url: 'https://example.com/page', urlSource: 'extension_location', fetchedUrl: 'https://example.com/page', httpStatus: 200, httpStatusSource: 'extension_navigation', httpStatusAvailability: 'available', indexability: 'indexable', indexabilityReason: 'No noindex directive was detected and robots.txt permits Googlebot for the audited path.', indexabilitySource: 'robots_txt', canonicalUrl: 'https://example.com/page', canonicalStatus: 'self-referencing', canonicalSource: 'dom_link', canonicalEvidence: 'The captured canonical matches the audited URL.', pageType: 'article', pageTypeConfidence: 'high', pageTypeEvidence: ['Article schema present'] } }, geoAeo: [] } }, categories: [{ label: 'On-page', score: 85, checks: 2, passed: 1, failed: 1, source: 'CALCULATED' }], issues: [{ id: 'i-1', severity: 'critical', category: 'On-page', title: 'Missing canonical', detected: 'No canonical detected', why: 'Canonical controls duplication', recommendation: 'Add a self-referencing canonical', evidence: ['head'] }], headings: [{ level: 1, text: 'Example' }], links: [{ anchor: 'Docs', absolute_url: 'https://example.com/docs', link_type: 'internal' }], images: [{ src: 'https://example.com/image.png', alt: 'Example image' }], schema: [], resources: [], performance: [], provenance: [] };

describe('normalized real-audit exports', () => {
  it('uses one saved audit object for report identity, exact issues, and complete export datasets', () => { const report = normalizedAuditReport(saved); const csv = exportCsvSets(report); expect(report.metadata.auditId).toBe('aud_123'); expect(report.pageEssentials.httpStatus).toBe(200); expect(report.issues[0].title).toBe('Missing canonical'); expect(exportReadiness(report).ready).toBe(true); expect(csv['00-page-essentials.csv']).toContain('extension_navigation'); expect(csv['02-issues.csv']).toContain('Missing canonical'); expect(Object.keys(csv)).toEqual(expect.arrayContaining(['08-categories.csv', '09-performance.csv', '10-geo-aeo.csv', '11-provenance.csv', '12-source-capture.csv', '13-security.csv', '14-detail.csv'])); });
  it('creates professional filenames and offline HTML from the same persisted values', () => { const report = normalizedAuditReport(saved); expect(exportFileBase(report)).toContain('example.com'); const html = standaloneHtml(report); expect(html).toContain('Page Essentials'); expect(html).toContain('extension_navigation'); expect(html).toContain('Missing canonical'); expect(html).toContain('https://example.com/docs'); });
  it('preserves oversized saved evidence in lossless XLSX long-text chunks instead of failing on Excel limits', () => { const report = normalizedAuditReport({ ...saved, audit: { ...saved.audit, payload: { detail: { capturedHtml: 'x'.repeat(33_500) }, geoAeo: [] } } }); const data = excelExportData(report); expect(data.longText.length).toBeGreaterThan(1); expect(data.longText.map(row => row[2]).join('')).toContain('x'.repeat(33_500)); expect(JSON.stringify(data.sheets)).toContain('Stored losslessly in Long Text'); });
});
