import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import type { SavedAudit } from '@/lib/audit-api';
import { auditCoverage, auditDetail, categoryContribution, list, number, record, savedPerformance, scoreMethod, securityStatus, sourceStatus, text, type AuditRecord } from '@/lib/audit-report';
import type { AuditSection } from '@/lib/audit-view';
import { CheckCircle2, Clipboard, Download, ExternalLink, FileArchive, FileCode2, FileJson2, FileSpreadsheet, FileText, LocateFixed, Printer, Radar, Search, ShieldCheck, Wifi } from 'lucide-react';
import { useMemo, useState } from 'react';
import { exportReadiness, exportReport, normalizedAuditReport, type ExportFormat } from '@/lib/audit-export';

type Props = {
  section: AuditSection;
  selected: SavedAudit;
  onLocate: (item: AuditRecord) => void;
  onOverlay: () => void;
  onOpenAudit: (id?: string, section?: AuditSection) => void;
  onConnect: () => void;
};

const title = (value: unknown, fallback = 'Not Available') => text(value) || fallback;
const label = (value: unknown) => String(value || 'Not Evaluated').replace(/[-_]/g, ' ');
const sentence = (value: unknown, fallback = 'No saved evidence is available for this audit.') => text(value) || fallback;
const asBoolean = (value: unknown) => value === true;

function Badge({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: 'good' | 'warn' | 'bad' | 'neutral' | 'info' }) {
  const tones = { good: 'border-emerald-300/30 bg-emerald-300/10 text-emerald-200', warn: 'border-amber-300/30 bg-amber-300/10 text-amber-100', bad: 'border-rose-300/30 bg-rose-300/10 text-rose-100', neutral: 'border-white/15 bg-white/5 text-slate-300', info: 'border-sky-300/30 bg-sky-300/10 text-sky-100' };
  return <span className={`inline-flex rounded-full border px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide ${tones[tone]}`}>{children}</span>;
}

function Metric({ name, value, note, tone = 'neutral' }: { name: string; value: React.ReactNode; note?: string; tone?: 'good' | 'warn' | 'bad' | 'neutral' }) {
  const border = tone === 'good' ? 'border-emerald-300/20' : tone === 'warn' ? 'border-amber-300/20' : tone === 'bad' ? 'border-rose-300/20' : 'border-white/10';
  return <div className={`rounded-xl border ${border} bg-[#0c1823]/70 p-4`}><p className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">{name}</p><strong className="mt-2 block text-2xl font-semibold text-white">{value}</strong>{note && <p className="mt-1 text-xs text-slate-400">{note}</p>}</div>;
}

function Empty({ title, detail }: { title: string; detail: string }) {
  return <Card className="border-dashed border-white/15 bg-[#0c1823]/70"><CardContent className="p-10 text-center"><p className="font-medium text-white">{title}</p><p className="mx-auto mt-2 max-w-2xl text-sm text-slate-400">{detail}</p></CardContent></Card>;
}

function SectionHeading({ title, detail, actions }: { title: string; detail: string; actions?: React.ReactNode }) {
  return <div className="mb-5 flex flex-wrap items-start justify-between gap-4"><div><p className="af-kicker">Audit Detail</p><h2 className="af-page-title">{title}</h2><p className="af-page-subtitle">{detail}</p></div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</div>;
}

function Evidence({ item }: { item: AuditRecord }) {
  const evidence = list(item.evidence);
  const rawEvidence = Array.isArray(item.evidence) ? item.evidence : [];
  return <div className="grid gap-4 border-t border-white/10 pt-4 text-sm md:grid-cols-2"><div><p className="font-medium text-white">What We Found</p><p className="mt-1 text-slate-400">{sentence(item.detected)}</p></div><div><p className="font-medium text-white">Expected</p><p className="mt-1 text-slate-400">{sentence(item.expected)}</p></div><div><p className="font-medium text-white">Why It Matters</p><p className="mt-1 text-slate-400">{sentence(item.why)}</p></div><div><p className="font-medium text-white">How To Fix It</p><p className="mt-1 text-slate-400">{sentence(item.recommendation || item.how)}</p></div>{(evidence.length > 0 || rawEvidence.length > 0) && <div className="md:col-span-2"><p className="font-medium text-white">Evidence</p><pre className="mt-2 max-h-56 overflow-auto rounded-lg border border-white/10 bg-black/20 p-3 text-xs text-slate-300">{JSON.stringify(rawEvidence, null, 2)}</pre></div>}</div>;
}

function Overview({ selected, onOpenAudit }: Pick<Props, 'selected' | 'onOpenAudit'>) {
  const audit = record(selected.audit); const detail = auditDetail(selected); const coverage = auditCoverage(selected); const categories = selected.categories.map(record); const contribution = categoryContribution(selected);
  const score = number(audit.overall_score); const head = record(detail.head); const page = record(detail.page); const captured = text(audit.captured_at);
  const categoryRows = (categories.length ? categories : contribution).map(item => {
    const checks = number(item.checks); const passed = number(item.passed); const ratio = checks === null ? 'Not Evaluated' : `${passed ?? 0} of ${checks}`;
    return <div key={String(item.category_id || item.id || item.label)} className="flex items-center justify-between gap-3 border-t border-white/10 py-3 first:border-t-0"><div><p className="font-medium text-white">{title(item.label || item.category_id)}</p><p className="text-xs text-slate-400">{checks === null ? 'No applicable checks captured' : `${number(item.failed) ?? 0} failed · ${ratio} passed`}</p></div><div className="text-right"><strong className="text-base text-white">{number(item.score) ?? '—'}</strong><p className="text-[10px] uppercase tracking-wide text-slate-500">Score</p></div></div>;
  });
  return <><SectionHeading title="Audit Overview" detail="The current saved audit, its coverage, scoring evidence, and page essentials." actions={<Button variant="outline" onClick={() => onOpenAudit(String(audit.id), 'issues')}>Review Issues</Button>} />
    <div className="grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><Card className="border-white/10 bg-[#0c1823]/80"><CardContent className="flex gap-6 p-6"><div className="grid h-28 w-28 shrink-0 place-items-center rounded-full border-[9px] border-primary/60 bg-[#0a1420]"><div className="text-center"><strong className="block text-3xl text-white">{score ?? '—'}</strong><span className="text-[10px] uppercase text-slate-400">SEO Score</span></div></div><div><p className="af-kicker">Saved Audit Evidence</p><h3 className="mt-1 text-2xl font-semibold text-white">{score === null ? 'Score Not Evaluated' : score >= 80 ? 'Strong Foundation' : score >= 50 ? 'Opportunities Identified' : 'Priority Fixes Needed'}</h3><p className="mt-2 text-sm text-slate-400">{title(audit.url, 'URL unavailable')}</p><p className="mt-3 text-xs text-slate-500">Captured: {captured ? new Date(captured).toLocaleString() : 'Not captured'}</p></div></CardContent></Card>
      <Card className="border-white/10 bg-[#0c1823]/80"><CardHeader><CardTitle className="text-base">Page Essentials</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p><span className="text-slate-400">HTTP Status</span><span className="float-right text-white">{number(page.status) ?? 'Not Captured'}</span></p><p><span className="text-slate-400">Indexability</span><span className="float-right text-white">{asBoolean(head.noindex) ? 'Noindex' : text(head.robotsMeta) || 'Not Flagged'}</span></p><p><span className="text-slate-400">Canonical</span><span className="float-right max-w-[55%] truncate text-white">{title(head.canonical, 'Not Captured')}</span></p><p><span className="text-slate-400">Page Type</span><span className="float-right text-white">{title(record(detail.pageType).type, 'Not Classified')}</span></p></CardContent></Card></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric name="Applicable" value={coverage.applicable} /><Metric name="Passed" value={coverage.pass} tone="good" /><Metric name="Critical" value={coverage.critical} tone={coverage.critical ? 'bad' : 'good'} /><Metric name="Warnings" value={coverage.warning} tone={coverage.warning ? 'warn' : 'good'} /><Metric name="Notices" value={coverage.notice} /><Metric name="Not Applicable" value={coverage.notApplicable} /></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><Card className="border-white/10 bg-[#0c1823]/80"><CardHeader><CardTitle className="text-base">Category Coverage</CardTitle><p className="text-xs text-slate-400">Passed / applicable checks from the saved engine result.</p></CardHeader><CardContent>{categoryRows.length ? categoryRows : <p className="text-sm text-slate-400">Category coverage was not captured for this audit.</p>}</CardContent></Card><Card className="border-white/10 bg-[#0c1823]/80"><CardHeader><CardTitle className="text-base">How This Score Was Calculated</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-slate-400">{sentence(scoreMethod(selected), 'The engine methodology was not retained in this audit payload.')}</p><div className="mt-4 rounded-lg border border-white/10 bg-black/20 p-3 text-xs text-slate-300">Coverage: {coverage.pass} passed of {coverage.applicable} applicable checks. {coverage.notApplicable} rules were not applicable and are excluded from the audit score.</div></CardContent></Card></div></>;
}

function Issues({ selected, onLocate }: Pick<Props, 'selected' | 'onLocate'>) {
  const [severity, setSeverity] = useState('all'); const [category, setCategory] = useState('all'); const [open, setOpen] = useState<string | null>(null);
  const items = selected.issues.map(record); const categories = Array.from(new Set(items.map(item => String(item.category || 'uncategorized'))));
  const visible = items.filter(item => (severity === 'all' || item.severity === severity || (severity === 'passed' && item.status === 'pass')) && (category === 'all' || item.category === category));
  const tone = (value: unknown) => value === 'critical' ? 'bad' : value === 'warning' ? 'warn' : value === 'pass' ? 'good' : 'info';
  return <><SectionHeading title="Issues" detail="Saved checks with exact findings, expectations, remediation, provenance, and available locator actions." /><div className="mb-4 flex flex-wrap gap-2">{['all', 'critical', 'warning', 'notice', 'passed'].map(value => <Button key={value} size="sm" variant={severity === value ? 'default' : 'outline'} onClick={() => setSeverity(value)}>{label(value)}</Button>)}</div><div className="mb-5 flex flex-wrap gap-2">{['all', ...categories].map(value => <Button key={value} size="sm" variant={category === value ? 'default' : 'outline'} onClick={() => setCategory(value)}>{label(value)}</Button>)}</div>{visible.length ? <div className="space-y-3">{visible.map((item, index) => { const key = String(item.id || index); const expanded = open === key; return <Card key={key} className="border-white/10 bg-[#0c1823]/80"><CardContent className="p-0"><button className="flex w-full items-center gap-3 p-4 text-left" onClick={() => setOpen(expanded ? null : key)}><Badge tone={tone(item.severity) as any}>{item.status === 'pass' ? 'Passed' : title(item.severity)}</Badge><strong className="min-w-0 flex-1 text-white">{title(item.title)}</strong><Badge>{title(item.category)}</Badge></button>{expanded && <div className="px-4 pb-4"><Evidence item={item} /><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={!item.locator} onClick={() => onLocate(item)}><LocateFixed className="mr-1 h-3.5 w-3.5" />Locate On Page</Button><span className="self-center text-xs text-slate-500">Source: {title(record(item.provenance).source, 'Not Captured')}</span></div></div>}</CardContent></Card>; })}</div> : <Empty title="No Checks Match These Filters" detail="This saved audit has no issue records for the selected severity and category." />}</>;
}

function Headings({ selected, onLocate, onOverlay }: Pick<Props, 'selected' | 'onLocate' | 'onOverlay'>) {
  const detail = auditDetail(selected); const stats = record(detail.headingStats); const headings = selected.headings.map(record); const [filter, setFilter] = useState('all'); const rows = headings.filter(row => filter === 'all' || String(row.level) === filter);
  return <><SectionHeading title="Headings" detail="Captured document hierarchy with level, question, empty-heading, and locator evidence." actions={<Button variant="outline" onClick={onOverlay}><Radar className="mr-2 h-4 w-4" />View H1–H6 On Page</Button>} /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric name="Total" value={number(stats.total) ?? headings.length} /><Metric name="H1" value={number(stats.h1) ?? headings.filter(h => h.level === 1).length} tone={(number(stats.h1) ?? 0) === 1 ? 'good' : 'warn'} /><Metric name="H2" value={number(stats.h2) ?? headings.filter(h => h.level === 2).length} /><Metric name="Level Skips" value={list(stats.skips).length} tone={list(stats.skips).length ? 'warn' : 'good'} /><Metric name="Duplicates" value={list(stats.duplicates).length} tone={list(stats.duplicates).length ? 'warn' : 'good'} /><Metric name="Questions" value={number(stats.questions) ?? headings.filter(h => h.is_question).length} /></div><div className="my-5 flex flex-wrap gap-2">{['all', '1', '2', '3', '4', '5', '6'].map(value => <Button key={value} size="sm" variant={filter === value ? 'default' : 'outline'} onClick={() => setFilter(value)}>{value === 'all' ? 'All Levels' : `H${value}`}</Button>)}</div>{rows.length ? <Card className="border-white/10 bg-[#0c1823]/80"><CardContent className="divide-y divide-white/10 p-0">{rows.map((row, index) => <div key={String(row.id || index)} className="flex items-center gap-3 p-3" style={{ paddingLeft: `${16 + Math.max(0, (Number(row.level) - 1)) * 18}px` }}><Badge tone={Number(row.level) === 1 ? 'bad' : Number(row.level) === 2 ? 'info' : 'neutral'}>H{String(row.level || '—')}</Badge><p className="min-w-0 flex-1 text-sm text-white">{title(row.text, '(Empty Heading)')}</p>{asBoolean(row.is_question) && <Badge tone="info">Question</Badge>}<Button size="sm" variant="ghost" disabled={!row.locator} onClick={() => onLocate(row)}><LocateFixed className="mr-1 h-3.5 w-3.5" />Locate</Button></div>)}</CardContent></Card> : <Empty title="No Captured Heading Data" detail="This saved audit did not retain headings for the selected level." />}</>;
}

function Links({ selected, onLocate }: Pick<Props, 'selected' | 'onLocate'>) {
  const detail = auditDetail(selected); const stats = record(detail.linkStats); const [search, setSearch] = useState(''); const rows = selected.links.map(record).filter(row => JSON.stringify(row).toLowerCase().includes(search.toLowerCase()));
  return <><SectionHeading title="Links" detail="Captured internal and external links, destinations, anchor signals, and available locator evidence." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric name="Total" value={number(stats.total) ?? selected.links.length} /><Metric name="Internal" value={number(stats.internal) ?? selected.links.filter(row => row.link_type === 'internal').length} /><Metric name="External" value={number(stats.external) ?? selected.links.filter(row => row.link_type === 'external').length} /><Metric name="Nofollow" value={number(stats.nofollow) ?? selected.links.filter(row => row.nofollow).length} /><Metric name="Empty Anchor" value={number(stats.emptyAnchors) ?? selected.links.filter(row => !row.anchor).length} /></div><div className="my-5 flex max-w-xl items-center gap-2 rounded-lg border border-white/10 bg-[#0c1823] px-3"><Search className="h-4 w-4 text-slate-400" /><input className="w-full bg-transparent py-2 text-sm text-white outline-none placeholder:text-slate-500" placeholder="Search links, anchors, or destinations" value={search} onChange={event => setSearch(event.target.value)} /></div>{rows.length ? <Card className="overflow-hidden border-white/10 bg-[#0c1823]/80"><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b border-white/10 bg-white/[.03] text-xs uppercase tracking-wide text-slate-400"><tr><th className="p-3">Anchor</th><th className="p-3">Destination</th><th className="p-3">Type</th><th className="p-3">Rel</th><th className="p-3">Action</th></tr></thead><tbody>{rows.map((row, index) => { const href = text(row.absolute_url || row.href) || ''; return <tr key={String(row.id || index)} className="border-b border-white/[.06]"><td className="max-w-56 truncate p-3 text-white">{title(row.anchor, 'Empty Anchor')}</td><td className="max-w-80 truncate p-3"><a className="text-primary hover:underline" href={href || undefined} target="_blank" rel="noreferrer">{title(row.absolute_url || row.href)}</a></td><td className="p-3"><Badge>{title(row.link_type)}</Badge></td><td className="p-3 text-slate-400">{asBoolean(row.nofollow) ? 'Nofollow' : title(row.rel, 'Follow')}</td><td className="p-3"><Button size="sm" variant="ghost" disabled={!row.locator} onClick={() => onLocate(row)}><LocateFixed className="mr-1 h-3.5 w-3.5" />Locate</Button></td></tr>; })}</tbody></table></div></Card> : <Empty title="No Links Match Your Search" detail="No stored links matched this query." />}</>;
}

function Images({ selected, onLocate }: Pick<Props, 'selected' | 'onLocate'>) {
  const detail = auditDetail(selected); const stats = record(detail.imageStats); const rows = selected.images.map(record);
  return <><SectionHeading title="Images" detail="Actual image ALT, sizing, format, and loading evidence retained with this audit." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric name="Images" value={number(stats.total) ?? rows.length} /><Metric name="ALT Coverage" value={number(stats.altCoverage) === null ? '—' : `${number(stats.altCoverage)}%`} /><Metric name="Missing ALT" value={number(stats.altMissing) ?? rows.filter(row => row.alt_missing).length} tone={(number(stats.altMissing) ?? 0) ? 'bad' : 'good'} /><Metric name="Decorative" value={number(stats.altEmpty) ?? rows.filter(row => row.alt_empty).length} /><Metric name="Broken" value={number(stats.broken) ?? rows.filter(row => row.broken).length} tone={(number(stats.broken) ?? 0) ? 'bad' : 'good'} /><Metric name="Responsive" value={number(stats.srcset) ?? '—'} /></div>{rows.length ? <Card className="mt-5 overflow-hidden border-white/10 bg-[#0c1823]/80"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-white/10 bg-white/[.03] text-xs uppercase tracking-wide text-slate-400"><tr><th className="p-3">Image URL</th><th className="p-3">ALT</th><th className="p-3">Natural Size</th><th className="p-3">Format</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{rows.map((row, index) => <tr key={String(row.id || index)} className="border-b border-white/[.06]"><td className="max-w-80 truncate p-3"><a className="text-primary hover:underline" href={text(row.src) || undefined} target="_blank" rel="noreferrer">{title(row.src)}</a></td><td className="max-w-64 truncate p-3 text-white">{asBoolean(row.alt_missing) ? <Badge tone="bad">Missing</Badge> : asBoolean(row.alt_empty) ? <Badge>Decorative</Badge> : title(row.alt)}</td><td className="p-3 text-slate-400">{number(row.width) && number(row.height) ? `${row.width} × ${row.height}` : 'Not Captured'}</td><td className="p-3 text-slate-400">{title(row.format)}</td><td className="p-3">{asBoolean(row.broken) ? <Badge tone="bad">Broken</Badge> : <Badge tone="good">Observed</Badge>}</td><td className="p-3"><Button size="sm" variant="ghost" disabled={!row.locator} onClick={() => onLocate(row)}><LocateFixed className="mr-1 h-3.5 w-3.5" />Locate</Button></td></tr>)}</tbody></table></div></Card> : <Empty title="No Image Data Was Captured" detail="This audit did not contain stored image records." />}</>;
}

function Schema({ selected }: Pick<Props, 'selected'>) {
  const rows = selected.schema.map(record); const types = Array.from(new Set(rows.flatMap(row => Array.isArray(row.types) ? row.types.map(String) : [])));
  return <><SectionHeading title="Schema" detail="Captured structured-data blocks, detected types, and validation evidence." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric name="Blocks" value={rows.length} /><Metric name="Detected Types" value={types.length} /><Metric name="Valid" value={rows.filter(row => row.valid).length} tone="good" /><Metric name="Invalid" value={rows.filter(row => row.valid === false).length} tone={rows.some(row => row.valid === false) ? 'bad' : 'good'} /></div>{types.length > 0 && <Card className="mt-5 border-white/10 bg-[#0c1823]/80"><CardHeader><CardTitle className="text-base">Detected Types</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{types.map(type => <Badge key={type} tone="info">{type}</Badge>)}</CardContent></Card>}{rows.length ? <div className="mt-5 space-y-3">{rows.map((row, index) => <Card key={String(row.id || index)} className="border-white/10 bg-[#0c1823]/80"><CardContent className="p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-white">Block {Number(row.position) + 1 || index + 1}</strong><Badge tone={row.valid ? 'good' : 'bad'}>{row.valid ? 'Valid JSON' : 'Invalid JSON'}</Badge></div><p className="mt-2 text-sm text-slate-400">Types: {Array.isArray(row.types) && row.types.length ? row.types.map(String).join(', ') : 'No @type Captured'}</p>{text(row.error) && <p className="mt-2 text-sm text-rose-200">{text(row.error)}</p>}<pre className="mt-3 max-h-56 overflow-auto rounded-lg border border-white/10 bg-black/20 p-3 text-xs text-slate-300">{JSON.stringify(record(row.payload), null, 2)}</pre></CardContent></Card>)}</div> : <Empty title="No Structured Data Was Captured" detail="The saved audit did not contain JSON-LD, Microdata, or RDFa entities." />}</>;
}

function Geo({ selected }: Pick<Props, 'selected'>) {
  const detail = auditDetail(selected); const robots = record(detail.robots); const bots = list(robots.bots); const llms = list(detail.llms); const content = record(detail.content); const geoIssues = selected.issues.map(record).filter(item => String(item.category).toLowerCase().includes('geo'));
  return <><SectionHeading title="GEO / AEO" detail="Captured answer-readiness signals and crawler-access evidence. These signals do not guarantee rankings." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric name="GEO Issues" value={geoIssues.length} tone={geoIssues.length ? 'warn' : 'good'} /><Metric name="Question Headings" value={number(record(detail.headingStats).questions) ?? '—'} /><Metric name="Lists" value={number(content.lists) ?? '—'} /><Metric name="Tables" value={number(content.tables) ?? '—'} /></div><div className="mt-5 grid gap-5 xl:grid-cols-2"><Card className="border-white/10 bg-[#0c1823]/80"><CardHeader><CardTitle className="text-base">AI Crawler Access</CardTitle><p className="text-xs text-slate-400">Parsed from saved robots.txt evidence.</p></CardHeader><CardContent className="space-y-3">{bots.length ? bots.map((bot, index) => <div key={String(bot.name || index)} className="flex justify-between border-b border-white/10 pb-2 last:border-0"><span className="text-white">{title(bot.name)}</span><Badge tone={bot.allowed === true ? 'good' : bot.allowed === false ? 'bad' : 'neutral'}>{bot.allowed === true ? 'Allowed' : bot.allowed === false ? 'Blocked' : 'Unknown'}</Badge></div>) : <p className="text-sm text-slate-400">Crawler rules were not captured for this audit.</p>}</CardContent></Card><Card className="border-white/10 bg-[#0c1823]/80"><CardHeader><CardTitle className="text-base">llms.txt And Related Files</CardTitle></CardHeader><CardContent className="space-y-3">{llms.length ? llms.map((file, index) => <div key={String(file.file || index)} className="flex justify-between border-b border-white/10 pb-2 last:border-0"><span className="text-white">{title(file.file)}</span><Badge tone={file.state === 'FOUND' ? 'good' : file.state === 'UNREACHABLE' ? 'warn' : 'neutral'}>{title(file.state)}</Badge></div>) : <p className="text-sm text-slate-400">No llms-related file checks were retained for this audit.</p>}</CardContent></Card></div>{geoIssues.length ? <div className="mt-5"><Issues selected={{ ...selected, issues: geoIssues as any }} onLocate={() => {}} /></div> : <Card className="mt-5 border-white/10 bg-[#0c1823]/80"><CardContent className="p-5 text-sm text-slate-400">No GEO/AEO issue records were stored for this audit.</CardContent></Card>}</>;
}

function Performance({ selected }: Pick<Props, 'selected'>) {
  const rows = savedPerformance(selected); return <><SectionHeading title="Performance" detail="Saved browser, lab, and field data remain separate and source-labelled." />{rows.length ? <div className="space-y-5">{rows.map((row, index) => { const metrics = record(row.metrics); const source = title(row.source); return <Card key={String(row.id || index)} className="border-white/10 bg-[#0c1823]/80"><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle className="text-base">{source} Data</CardTitle><p className="mt-1 text-xs text-slate-400">Strategy: {title(row.strategy, 'Default')}</p></div><Badge tone={source === 'FIELD' ? 'info' : source === 'LAB' ? 'warn' : 'good'}>{source}</Badge></div></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{['LCP', 'INP', 'CLS', 'FCP', 'TBT', 'TTFB'].map(metric => <Metric key={metric} name={metric} value={number(record(metrics[metric]).value) ?? number(metrics[metric]) ?? '—'} />)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric name="Performance" value={number(row.performance_score) ?? '—'} /><Metric name="Accessibility" value={number(row.accessibility_score) ?? '—'} /><Metric name="Best Practices" value={number(row.best_practices_score) ?? '—'} /><Metric name="SEO" value={number(row.seo_score) ?? '—'} /></div></CardContent></Card>; })}</div> : <Empty title="No Saved Performance Data" detail="This audit has no persisted LAB, FIELD, or browser performance result. No score has been fabricated." />}</>;
}

function Accessibility({ selected }: Pick<Props, 'selected'>) {
  const data = record(auditDetail(selected).accessibility); const rows: [string, unknown, unknown, string][] = [['Form fields with labels', data.inputs, data.unlabelledInputs, 'Unlabelled'], ['Buttons with accessible names', data.buttons, data.namelessButtons, 'Nameless'], ['Links with accessible names', data.links, data.namelessLinks, 'Nameless'], ['Iframes with titles', data.iframes, data.untitledIframes, 'Untitled'], ['Navigation landmarks', record(data.landmarks).nav, null, ''], ['ARIA roles', data.ariaRoles, null, '']];
  return <><SectionHeading title="Accessibility" detail="DOM-visible accessibility signals. Human and assistive-technology testing remains necessary for issues that cannot be verified automatically." /><Card className="border-white/10 bg-[#0c1823]/80"><CardContent className="divide-y divide-white/10 p-0">{rows.some(row => row[1] !== undefined) ? rows.map(([name, total, problem, issue]) => <div key={name} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-medium text-white">{name}</p><p className="text-xs text-slate-400">{problem === null ? 'Captured DOM signal' : `${number(problem) ?? 0} ${issue.toLowerCase()} of ${number(total) ?? 0}`}</p></div><Badge tone={(number(problem) ?? 0) > 0 ? 'warn' : 'good'}>{total === undefined ? 'Not Captured' : `${number(total) ?? 0}`}</Badge></div>) : <Empty title="No Accessibility Signals Were Captured" detail="This audit did not retain DOM accessibility data." />}</CardContent></Card></>;
}

function Technical({ selected, securityOnly = false }: Pick<Props, 'selected'> & { securityOnly?: boolean }) {
  const detail = auditDetail(selected); const page = record(detail.page); const tech = record(detail.tech); const security = securityStatus(selected); const headers: [string, string][] = [['HSTS', 'hsts'], ['Content-Security-Policy', 'csp'], ['X-Content-Type-Options', 'contentTypeOptions'], ['Referrer-Policy', 'referrerPolicy'], ['Frame Protection', 'frameOptions'], ['Permissions-Policy', 'permissionsPolicy']];
  if (securityOnly) return <><SectionHeading title="Security" detail="Response security headers captured during this audit. Browser-limited checks remain explicitly unavailable." />{security.available ? <Card className="border-white/10 bg-[#0c1823]/80"><CardContent className="divide-y divide-white/10 p-0">{headers.map(([name, key]) => { const header = record(security.security[key]); return <div key={key} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-medium text-white">{name}</p><p className="max-w-2xl truncate text-xs text-slate-400">{title(header.value, 'Not Set')}</p></div><Badge tone={asBoolean(header.present) ? 'good' : 'warn'}>{asBoolean(header.present) ? 'Set' : 'Not Set'}</Badge></div>; })}</CardContent></Card> : <Empty title="Security Headers Not Available" detail={security.reason} />}</>;
  return <><SectionHeading title="Technical" detail="Captured delivery, crawlability, indexability, robots, sitemap, and rendering signals." /><Card className="border-white/10 bg-[#0c1823]/80"><CardContent className="divide-y divide-white/10 p-0">{[['HTTPS', page.isHttps === true ? 'Secure' : page.isHttps === false ? 'Not Secure' : 'Not Captured'], ['Mixed Content', number(tech.mixedContentCount) === null ? 'Not Captured' : number(tech.mixedContentCount) === 0 ? 'None' : `${tech.mixedContentCount} insecure resources`], ['TTFB', number(page.ttfbMs) === null ? 'Not Captured' : `${page.ttfbMs} ms`], ['DOM Elements', number(page.domNodes) ?? 'Not Captured'], ['Language', title(page.lang)], ['Charset', title(page.charset)]].map(([name, value]) => <div key={String(name)} className="flex justify-between gap-4 p-4"><span className="font-medium text-white">{name}</span><span className="text-right text-slate-400">{value}</span></div>)}</CardContent></Card><div className="mt-5"><Technical selected={selected} securityOnly /></div></>;
}

function Resources({ selected, sourceView = false, onOpenAudit }: Pick<Props, 'selected' | 'onOpenAudit'> & { sourceView?: boolean }) {
  const [query, setQuery] = useState(''); const status = sourceStatus(selected); const rows = selected.resources.map(record); const filtered = rows.filter(row => JSON.stringify(row).toLowerCase().includes(query.toLowerCase()));
  if (sourceView) { const lines = status.html?.split('\n') || []; const visible = lines.filter(line => !query || line.toLowerCase().includes(query.toLowerCase())); return <><SectionHeading title="HTML Source" detail="Server HTML retained in this saved audit. This is displayed only when it was captured." /><div className="mb-4 flex max-w-xl items-center gap-2 rounded-lg border border-white/10 bg-[#0c1823] px-3"><Search className="h-4 w-4 text-slate-400" /><input className="w-full bg-transparent py-2 text-sm text-white outline-none placeholder:text-slate-500" placeholder="Search captured source" value={query} onChange={event => setQuery(event.target.value)} /></div>{status.available ? <Card className="border-white/10 bg-[#0c1823]/80"><CardContent className="p-0"><div className="max-h-[65vh] overflow-auto p-4"><pre className="text-xs leading-6 text-slate-300">{visible.map((line, index) => <div key={index}><span className="mr-4 inline-block w-10 select-none text-right text-slate-600">{index + 1}</span>{line}</div>)}</pre></div></CardContent></Card> : <Empty title="HTML Source Not Available" detail={status.reason} />}</>; }
  return <><SectionHeading title="Resources" detail="Browser resource timing and file evidence retained in this saved audit." actions={<Button variant="outline" onClick={() => onOpenAudit(String(record(selected.audit).id), 'source')}>View HTML Source</Button>} /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric name="Requests" value={rows.length} /><Metric name="Third Party" value={rows.filter(row => row.cross_origin).length} /><Metric name="Render Blocking" value={rows.filter(row => row.render_blocking_candidate).length} /><Metric name="Known Transfer" value={`${Math.round(rows.reduce((sum, row) => sum + (number(row.transfer_bytes) || 0), 0) / 1024)} KB`} /></div><div className="my-5 flex max-w-xl items-center gap-2 rounded-lg border border-white/10 bg-[#0c1823] px-3"><Search className="h-4 w-4 text-slate-400" /><input className="w-full bg-transparent py-2 text-sm text-white outline-none placeholder:text-slate-500" placeholder="Search resources" value={query} onChange={event => setQuery(event.target.value)} /></div>{filtered.length ? <Card className="overflow-hidden border-white/10 bg-[#0c1823]/80"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-white/10 bg-white/[.03] text-xs uppercase tracking-wide text-slate-400"><tr><th className="p-3">URL</th><th className="p-3">Type</th><th className="p-3">Size</th><th className="p-3">Duration</th><th className="p-3">Origin</th></tr></thead><tbody>{filtered.map((row, index) => <tr key={String(row.id || index)} className="border-b border-white/[.06]"><td className="max-w-[480px] truncate p-3"><a className="text-primary hover:underline" href={text(row.url) || undefined} target="_blank" rel="noreferrer">{title(row.url)}</a></td><td className="p-3 text-slate-300">{title(row.kind)}</td><td className="p-3 text-slate-400">{number(row.transfer_bytes) === null ? 'Unknown' : `${Math.round((number(row.transfer_bytes) || 0) / 1024)} KB`}</td><td className="p-3 text-slate-400">{number(row.duration_ms) === null ? 'Not Captured' : `${row.duration_ms} ms`}</td><td className="p-3"><Badge tone={asBoolean(row.cross_origin) ? 'warn' : 'good'}>{asBoolean(row.cross_origin) ? 'Third Party' : 'Same Origin'}</Badge></td></tr>)}</tbody></table></div></Card> : <Empty title="No Resource Data Was Captured" detail="This audit contains no saved resource timing records." />}</>;
}

function Reports({ selected, onOpenAudit }: Pick<Props, 'selected' | 'onOpenAudit'>) {
  const audit = record(selected.audit); const report = useMemo(() => normalizedAuditReport(selected), [selected]); const readiness = exportReadiness(report); const [working, setWorking] = useState<ExportFormat | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const copy = async () => navigator.clipboard.writeText([
    'AuditFlux Saved Audit', `URL: ${title(audit.url)}`, `Score: ${number(audit.overall_score) ?? 'Not Evaluated'}`,
    `Captured: ${title(audit.captured_at, 'Not Captured')}`, `Issues: ${report.issues.length}`,
    ...selected.categories.map(record).map(category => `${title(category.label || category.category_id)}: ${number(category.score) ?? 'Not Evaluated'} (${number(category.passed) ?? 0}/${number(category.checks) ?? 0} passed)`),
  ].join('\n'));
  const generate = async (format: ExportFormat) => { setWorking(format); setNotice(`Preparing ${format.toUpperCase()} from the current saved audit…`); try { await exportReport(format, report); setNotice(`${format.toUpperCase()} is ready for download.`); } catch (error) { setNotice(error instanceof Error ? error.message : 'The export could not be generated from this saved audit.'); } finally { setWorking(null); } };
  const formats: { id: ExportFormat; title: string; description: string; modules: string; Icon: typeof FileText }[] = [
    { id: 'pdf', title: 'PDF', description: 'Client-facing audit with executive summary, action plan, issues, and evaluated modules.', modules: 'Summary · Action Plan · Issues · Modules', Icon: FileText },
    { id: 'xlsx', title: 'Excel / XLSX', description: 'Structured workbook with separate real-data worksheets for SEO teams.', modules: 'Summary · Issues · Links · Images · Raw Data', Icon: FileSpreadsheet },
    { id: 'csv', title: 'Complete CSV', description: 'ZIP of separately structured CSV datasets for analysis and workflows.', modules: 'Issues · Headings · Links · Images · Resources', Icon: FileArchive },
    { id: 'docx', title: 'Word / DOCX', description: 'Editable client-ready document with evidence and recommendations.', modules: 'Cover · Action Plan · Issues', Icon: FileText },
    { id: 'html', title: 'Standalone HTML', description: 'Offline interactive report with real links, navigation, and saved evidence.', modules: 'All Evaluated Modules · Source When Captured', Icon: FileCode2 },
    { id: 'json', title: 'JSON', description: 'Complete machine-readable normalized report object for technical workflows.', modules: 'Audit Metadata · Evidence · Provenance', Icon: FileJson2 },
  ];
  return <><SectionHeading title="Export & Report Center" detail="Generate complete professional exports from this one saved audit. No report data is simulated or recalculated here." actions={<><Button variant="outline" onClick={() => onOpenAudit(String(audit.id), 'overview')}><ExternalLink className="mr-2 h-4 w-4" />View Full Report</Button><Button variant="outline" onClick={() => void copy()}><Clipboard className="mr-2 h-4 w-4" />Copy Summary</Button></>} />
    <Card className="border-primary/25 bg-gradient-to-br from-[#0c1b2a] to-[#0c1823]"><CardContent className="grid gap-4 p-6 lg:grid-cols-[1fr_auto]"><div><p className="af-kicker">Current Saved Audit</p><h3 className="mt-1 break-all text-lg font-semibold text-white">{title(audit.url)}</h3><p className="mt-2 text-sm text-slate-400">Audit ID: {title(audit.id)} · Scanned: {title(audit.captured_at)}</p></div><div className="grid grid-cols-2 gap-3 text-right sm:grid-cols-3"><Metric name="Score" value={report.metadata.overallScore ?? '—'} /><Metric name="Issues" value={report.issues.length} /><Metric name="Coverage" value={`${report.coverage.pass}/${report.coverage.applicable}`} /></div></CardContent></Card>
    {!readiness.ready && <Card className="mt-5 border-amber-300/30 bg-amber-300/10"><CardContent className="p-4 text-sm text-amber-100">This audit cannot be exported yet because its {readiness.missing.join(', ')} is unavailable. AuditFlux will not generate a partial report with invented values.</CardContent></Card>}
    {notice && <Card className="mt-5 border-sky-300/20 bg-sky-300/10"><CardContent className="flex items-center gap-3 p-4 text-sm text-sky-100">{working && <Radar className="h-5 w-5 animate-spin" />}{notice}</CardContent></Card>}
    <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{formats.map(format => <Card key={format.id} className="border-white/10 bg-[#0c1823]/80"><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div className="grid h-10 w-10 place-items-center rounded-lg border border-primary/30 bg-primary/10 text-primary"><format.Icon className="h-5 w-5" /></div><Badge tone="info">Real Data</Badge></div><h3 className="mt-5 text-lg font-semibold text-white">{format.title}</h3><p className="mt-2 min-h-12 text-sm text-slate-400">{format.description}</p><p className="mt-4 text-xs text-slate-500">Includes: {format.modules}</p><Button className="mt-5 w-full" variant={format.id === 'pdf' ? 'default' : 'outline'} disabled={!readiness.ready || working !== null} onClick={() => void generate(format.id)}>{working === format.id ? <><Radar className="mr-2 h-4 w-4 animate-spin" />Generating…</> : <><Download className="mr-2 h-4 w-4" />Export {format.title}</>}</Button></CardContent></Card>)}</div></>;
}

export default function UnifiedAuditSection(props: Props) {
  const view = useMemo(() => props.section, [props.section]);
  if (view === 'overview') return <Overview selected={props.selected} onOpenAudit={props.onOpenAudit} />;
  if (view === 'issues') return <Issues selected={props.selected} onLocate={props.onLocate} />;
  if (view === 'headings') return <Headings selected={props.selected} onLocate={props.onLocate} onOverlay={props.onOverlay} />;
  if (view === 'links') return <Links selected={props.selected} onLocate={props.onLocate} />;
  if (view === 'images') return <Images selected={props.selected} onLocate={props.onLocate} />;
  if (view === 'schema') return <Schema selected={props.selected} />;
  if (view === 'geo') return <Geo selected={props.selected} />;
  if (view === 'performance') return <Performance selected={props.selected} />;
  if (view === 'accessibility') return <Accessibility selected={props.selected} />;
  if (view === 'technical') return <Technical selected={props.selected} />;
  if (view === 'security') return <Technical selected={props.selected} securityOnly />;
  if (view === 'resources') return <Resources selected={props.selected} onOpenAudit={props.onOpenAudit} />;
  if (view === 'source') return <Resources selected={props.selected} sourceView onOpenAudit={props.onOpenAudit} />;
  if (view === 'reports') return <Reports selected={props.selected} onOpenAudit={props.onOpenAudit} />;
  return <Empty title="This Audit Area Is Not Connected Yet" detail="No unified section is registered for this route." />;
}
